name: Anti-Phishing Check

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for suspicious links
        uses: actions/github-script@v7
        with:
          script: |
            // Determine the context (issue, PR, or comment)
            let body;
            let number;
            
            if (context.payload.issue) {
              body = context.payload.issue.body;
              number = context.payload.issue.number;
            } else if (context.payload.pull_request) {
              body = context.payload.pull_request.body;
              number = context.payload.pull_request.number;
            } else if (context.payload.comment) {
              body = context.payload.comment.body;
              number = context.payload.issue ? context.payload.issue.number : context.payload.pull_request.number;
            }

            if (!body) return;
            
            // List of allowed domains
            const allowedDomains = [
              'github.com',
              'githubusercontent.com',
              'arch.network'
            ];
            
            // Regular expression to find URLs
            const urlRegex = /(https?:\/\/[^\s]+)/g;
            const urls = body.match(urlRegex) || [];
            
            let suspiciousUrls = [];
            urls.forEach(url => {
              try {
                const domain = new URL(url).hostname;
                if (!allowedDomains.some(allowed => domain.endsWith(allowed))) {
                  suspiciousUrls.push(url);
                }
              } catch (e) {
                suspiciousUrls.push(url);
              }
            });
            
            if (suspiciousUrls.length > 0) {
              const warning = `⚠️ This ${context.payload.pull_request ? 'pull request' : 'issue'}/comment contains potentially suspicious links:\n${suspiciousUrls.join('\n')}\n\nPlease review these links carefully.`;
              
              // Function to create comment
              const createComment = context.payload.pull_request ? 
                github.rest.issues.createComment : 
                github.rest.issues.createComment;
              
              // Add warning comment
              await createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                body: warning
              });
              
              // Add warning label
              const addLabels = context.payload.pull_request ?
                github.rest.issues.addLabels :
                github.rest.issues.addLabels;
              
              await addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                labels: ['suspicious-links']
              });
            }
